title: Github Page Blog
author: Me
email: me@github.com
description: > # this means to ignore newlines until "baseurl:"
  Default page for Github page.

# social links
twitter_username: cn10xy # DO NOT include the @ character, or else the build will fail!
github_username:  cn10xy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
